name: qadha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  auto_route: ^4.2.1
  material_design_icons_flutter: ^5.0.6996
  get_it: ^7.2.0
  stacked: ^2.3.15
  injectable: ^1.5.3
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.3
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter           
  auto_route_generator:            
  build_runner:              

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
  - family: Inter Bold
    fonts:
      - asset: assets/fonts/Inter-Bold.ttf
  - family: Inter SemiBold
    fonts:
      - asset: assets/fonts/Inter-SemiBold.ttf
  - family: Inter Regular
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf