name: qadha
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  auto_route: ^4.2.1
  material_design_icons_flutter: ^5.0.6996
  pin_code_fields: ^7.4.0
  flutter_svg: ^1.1.3
  percent_indicator: ^4.2.2
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.55.1
  cloud_firestore: ^3.4.6
  flutter_riverpod: ^1.0.4
  blur: ^3.1.0
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.9
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter           
  auto_route_generator:            
  build_runner:              

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/blue/

  fonts:
  - family: Inter Bold
    fonts:
      - asset: assets/fonts/Inter-Bold.ttf
  - family: Inter SemiBold
    fonts:
      - asset: assets/fonts/Inter-SemiBold.ttf
  - family: Inter Regular
    fonts:
      - asset: assets/fonts/Inter-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/adaptive_logo.png"

flutter_native_splash:
  color: "#3741ba"
  image: assets/images/qadha_white.png